import Link from "next/link";
export default function Journals() {
  return (
    <main>
      <h1>Journals</h1>{" "}
      {
        // return (
        <div className="container mx-auto px-4">
          <nav className="flex justify-between items-center py-4">
            <div className="text-xl font-semibold">Atul K</div>
            <div className="hidden md:flex space-x-4">
              <Link className="block" href="#"></Link>
              <Link className="block" href="#"></Link>
              <div className="relative group">
                <Link className="block" href="#"></Link>
                <div className="absolute hidden group-hover:block bg-white shadow-lg p-2">
                  <Link className="block px-4 py-2 text-sm hover:bg-gray-100" href="#"></Link>
                  <Link className="block px-4 py-2 text-sm hover:bg-gray-100" href="#"></Link>
                </div>
              </div>
              <Link className="block" href="#"></Link>
              <Link className="block" href="#"></Link>
              <Link className="block" href="#"></Link>
              <Link className="block" href="#"></Link>
              <Link className="block" href="#"></Link>
              <div className="relative group">
                <Link className="block" href="#"></Link>
                <div className="absolute hidden group-hover:block bg-white shadow-lg p-2">
                  <Link className="block px-4 py-2 text-sm hover:bg-gray-100" href="#"></Link>
                  <Link className="block px-4 py-2 text-sm hover:bg-gray-100" href="#"></Link>
                </div>
              </div>
              {/* <IconSearch className="h-6 w-6" /> */}
            </div>
          </nav>
          <header className="my-10">
            <h1 className="text-5xl font-bold">publications</h1>
            <p className="text-gray-600 mt-2">publications by categories in reversed chronological order. generated by jekyll-scholar.</p>
          </header>
          <main>
            <article className="mb-8">
              <div className="flex items-center space-x-4 mb-2">
                <img
                  alt="Publication Cover"
                  className="h-24 w-24"
                  height="100"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width="100"
                />
                <div>
                  <h2 className="text-lg font-semibold">Letters on wave mechanics</h2>
                  <p className="text-gray-600">Albert Einstein, Erwin Schrödinger, Max Planck, and 2 more authors</p>
                  <span className="text-gray-400">1967</span>
                </div>
              </div>
              {/* <Button className="bg-blue-500 text-white">BIB</Button> */}
            </article>
            <article className="mb-8">
              <div className="flex items-center space-x-4 mb-2">
                <img
                  alt="Publication Cover"
                  className="h-24 w-24"
                  height="100"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width="100"
                />
                <div>
                  <h2 className="text-lg font-semibold">Investigations on the Theory of the Brownian Movement</h2>
                  <p className="text-gray-600">Albert Einstein</p>
                  <span className="text-gray-400">1956</span>
                </div>
              </div>
              {/* <Button className="bg-blue-500 text-white">BIB</Button> */}
            </article>
            <article className="mb-8">
              <div className="flex items-center space-x-4 mb-2">
                <img
                  alt="Publication Cover"
                  className="h-24 w-24"
                  height="100"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width="100"
                />
                <div>
                  <h2 className="text-lg font-semibold">The meaning of relativity</h2>
                  <p className="text-gray-600">Albert Einstein, and AH Taub</p>
                  <span className="text-gray-400">1950</span>
                </div>
              </div>
              {/* <Button className="bg-blue-500 text-white">BIB</Button> */}
            </article>
            <article className="mb-8">
              <div className="flex items-center space-x-4 mb-2">
                <img
                  alt="Publication Cover"
                  className="h-24 w-24"
                  height="100"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                  }}
                  width="100"
                />
                <div>
                  <h2 className="text-lg font-semibold">Can Quantum-Mechanical Description of Physical Reality Be Considered Complete?</h2>
                  <p className="text-gray-600">A. Einstein, B. Podolsky, and N. Rosen</p>
                  <span className="text-gray-400">1935</span>
                </div>
              </div>
              {/* <Button className="bg-blue-500 text-white">BIB</Button> */}
            </article>
          </main>
        </div>
      }
    </main>
  );
}
